In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:\Users\Iniya\Downloads\Database_Formula_1.csv")

# Create a copy for processing
f1 = df.copy()

# Display original dataset information
print("Original Shape:", df.shape)
print("\nColumn Names:")
print(f1.columns.tolist())

print("\nMissing Values:")
print(f1.isnull().sum())

# Remove duplicate records
f1.drop_duplicates(inplace=True)

# Standardize column names
f1.columns = (
    f1.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

print("\nCleaned Shape:", f1.shape)

# Display first 5 rows
f1.head()

C:\Users\Iniya\AppData\Local\Temp\ipykernel_4028\1256520224.py:4: DtypeWarning: Columns (0: Altitude, 1: Race Number) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Iniya\Downloads\Database_Formula_1.csv")

Original Shape: (25840, 34)

Column Names:
['Year', 'Round', 'Grand Prix', 'Date', 'Starting Time', 'Circuit', 'Location', 'Country', 'lat', 'lng', 'Altitude', 'Position', 'Position Order', 'Firstname', 'Lastname', 'Code', 'Nationality', 'Race Number', 'Date of Birth', 'Team', 'Team nationality', 'Laps', 'Total Time', 'Grid', 'Points', 'Fastest Lap', 'Av. Fastest Lap (km/h)', 'fastestLap', 'rank', 'Notes', 'Qualifying Position', 'Q1 Time', 'Q2 Time', 'Q3 Time']

Missing Values:
Year                          0
Round                         0
Grand Prix                    0
Date                          0
Starting Time                 0
Circuit                       0
Location                      0
Country                       0
lat                           0
lng                           0
Altitude                      0
Position                      0
Position Order                0
Firstname                     0
Lastname                      0
Code                          0
Nationality                   0
Race Number                   0
Date of Birth                 0
Team                          0
Team nationality              0
Laps                          0
Total Time                    0
Grid                          0
Points                        0
Fastest Lap                   0
Av. Fastest Lap (km/h)        0
fastestLap                    0
rank                          0
Notes                         0
Qualifying Position       16265
Q1 Time                   16273
Q2 Time                   16416
Q3 Time                   16564
dtype: int64

Cleaned Shape: (25840, 34)

,year,round,grand_prix,date,starting_time,circuit,location,country,lat,lng,...,points,fastest_lap,av._fastest_lap_(km/h),fastestlap,rank,notes,qualifying_position,q1_time,q2_time,q3_time
0,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,9.0,\N,\N,\N,\N,Finished,NaN,NaN,NaN,NaN
1,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,6.0,\N,\N,\N,\N,Finished,NaN,NaN,NaN,NaN
2,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,4.0,\N,\N,\N,\N,Finished,NaN,NaN,NaN,NaN
3,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,3.0,\N,\N,\N,\N,+2 Laps,NaN,NaN,NaN,NaN
4,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,2.0,\N,\N,\N,\N,+2 Laps,NaN,NaN,NaN,NaN

In [2]:
!pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.52-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.5-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\miniconda3\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.52-cp314-cp314-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 1.1 MB/s eta 0:00:02
   --------- ------------------------------ 0.5/2.2 MB 1.1 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.2 MB 1.1 MB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.2 MB 1.1 MB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.2 MB 1.1 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.2 MB 1.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.2 MB 975.1 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.2 MB 937.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.2 MB 937.8 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 924.5 kB/s  0:00:02
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.5-cp314-cp314-win_amd64.whl (327 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [pymysql]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.5 pymysql-1.2.0 sqlalchemy-2.0.52

In [3]:
from sqlalchemy import create_engine

In [4]:
username = "root"
password = "Iniya_15022006"
host = "localhost"
port = 3306
database = "f1_analytics"

In [5]:
db_engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [6]:
with db_engine.connect() as connection:
    print("Connected successfully!")

Connected successfully!

In [7]:
f1.to_sql(
    "f1_data",
    con=db_engine,
    if_exists="replace",
    index=False
)

25840

In [8]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM f1_data",
    db_engine
)

   total_rows
0       25840

In [9]:
pd.read_sql(
    "SELECT * FROM f1_data LIMIT 5",
    db_engine
)

,year,round,grand_prix,date,starting_time,circuit,location,country,lat,lng,...,points,fastest_lap,av._fastest_lap_(km/h),fastestlap,rank,notes,qualifying_position,q1_time,q2_time,q3_time
0,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,9.0,\N,\N,\N,\N,Finished,None,None,None,None
1,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,6.0,\N,\N,\N,\N,Finished,None,None,None,None
2,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,4.0,\N,\N,\N,\N,Finished,None,None,None,None
3,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,3.0,\N,\N,\N,\N,+2 Laps,None,None,None,None
4,1950,1,British Grand Prix,1950-05-13,\N,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,...,2.0,\N,\N,\N,\N,+2 Laps,None,None,None,None